rules = [
  OrganizeImports
]

OrganizeImports {
  blankLines = Manual
  coalesceToWildcardImportThreshold = null
  expandRelative = false
  groupExplicitlyImportedImplicitsSeparately = false
  groupedImports = Merge
  groups = [
    "*"
    "---"
    "scala."
    "---"
    "java."
  ]
  importSelectorsOrder = Ascii
  importsOrder = Ascii
  removeUnused = false
  targetDialect = Scala3
}
